version: 0.2.0.{build}-{branch}
image: Visual Studio 2017
configuration: Release
init:
- ps: '& ".\Scripts\Initialization.ps1"'
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 0.2.0.{build}
  assembly_file_version: 0.2.0.{build}
  assembly_informational_version: 0.2.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
on_success:
- ps: '& ".\Scripts\OnBuildSuccess.ps1"'
