version: 0.2.0-{branch}.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 0.2.0.{build}
  assembly_file_version: 0.2.0.{build}
  assembly_informational_version: 0.2.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: '& "Scripts\AfterBuild.ps1"'
# deploy:
# - provider: Environment
#   name: MyGet
# test if it will proceed to deployment when build fails
