version: 0.2.0.{build}-{branch}
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    if ($env:APPVEYOR_REPO_BRANCH -eq "master")

    {
        $newVersion = $env:APPVEYOR_BUILD_VERSION -replace "-$env:APPVEYOR_REPO_BRANCH"
        Update-AppveyorBuild -Version $newVersion
    }
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 0.2.0.{build}
  assembly_file_version: 0.2.0.{build}
  assembly_informational_version: 0.2.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
on_success:
- ps: '& ".\OnBuildSuccess.ps1"'
