version: 1.0.1-{branch}{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 1.0.1.{build}
  assembly_file_version: 1.0.1.{build}
  assembly_informational_version: 1.0.1.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: '& ".\AfterBuild.ps1"'
deploy:
- provider: Environment
  name: MyGet
  on:
    branch: master, dev
- provider: Environment
  name: NuGet
  on:
    branch: master
