version: 1.4.0-{branch}{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
skip_tags: true
skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - LICENSE.md
    - README.md
    - Run-UnitTests.ps1
image: Visual Studio 2017
build_script:
- ps: '& .\AppVeyor-Build.ps1'
deploy:
- provider: Environment
  name: MyGet
  on:
    SKIP_DEPLOYMENT: false
- provider: Environment
  name: NuGet
  on:
    branch: master
    SKIP_DEPLOYMENT: false
- provider: Environment
  name: GitHub Releases
  on:
    branch: master
    SKIP_DEPLOYMENT: false
