version: 0.2.0.{build}_{branch}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 0.2.0.{build}
  assembly_file_version: 0.2.0.{build}
  assembly_informational_version: 0.2.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a NotifyPropertyChangedBase.Net40.zip %APPVEYOR_BUILD_FOLDER%\NotifyPropertyChangedBase.Net40\bin\Release\**\*

    7z a NotifyPropertyChangedBase.Net45.zip %APPVEYOR_BUILD_FOLDER%\NotifyPropertyChangedBase.Net45\bin\Release\**\*

    7z a NotifyPropertyChangedBase.Uap.zip %APPVEYOR_BUILD_FOLDER%\NotifyPropertyChangedBase.Uap\bin\Release\**\*

    appveyor PushArtifact NotifyPropertyChangedBase.Net40.zip

    appveyor PushArtifact NotifyPropertyChangedBase.Net45.zip

    appveyor PushArtifact NotifyPropertyChangedBase.Uap.zip
