version: 0.2.0.{build}_{branch}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 0.2.0.{build}
  assembly_file_version: 0.2.0.{build}
  assembly_informational_version: 0.2.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: >-
    7z a NotifyPropertyChangedBase.Net40.zip NotifyPropertyChangedBase.Net40\bin\Release\**\*
    7z a NotifyPropertyChangedBase.Net45.zip NotifyPropertyChangedBase.Net45\bin\Release\**\*
    7z a NotifyPropertyChangedBase.Uap.zip NotifyPropertyChangedBase.Uap\bin\Release\**\*

    Push-AppveyorArtifact NotifyPropertyChangedBase.Net40.zip
    Push-AppveyorArtifact NotifyPropertyChangedBase.Net45.zip
    Push-AppveyorArtifact NotifyPropertyChangedBase.Uap.zip
artifacts:
- path: '*\bin\Release\**\*'
