version: 0.2.0.{build}-{branch}
branches:
  only:
  - master
  - dev
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 0.2.0.{build}
  assembly_file_version: 0.2.0.{build}
  assembly_informational_version: 0.2.0.{build}
before_build:
- ps: '& "Scripts\BeforeBuild.ps1"'
build:
  verbosity: minimal
after_build:
- ps: '& "Scripts\AfterBuild.ps1"'
deploy:
- provider: Environment
  name: MyGet
